# These parameters describe the vehicle geometry and motor connections:

vehicle:
  axles:
    front_axle:
      position_x: 0.8
      position_y: 0.0
      wheel_diameter: 0.3
      is_steered: true
      is_driven: true
      track: 0.7
      steering_hinge_offset: 0.06
      steering_velocity: 0.25
      steering_position_tolerance: 0.001
      left_hinge_joint: front_left_hinge_joint
      left_wheel_joint: front_left_wheel_joint
      right_hinge_joint: front_right_hinge_joint
      right_wheel_joint: front_right_wheel_joint
      steering:
        type: FourBarLinkageSteering
        steering_shaft_x: 0.7
        steering_shaft_y: 0.0
        steering_crank_length: 0.05
        steering_crank_angle: 0.524
        wheel_steering_arm_length: 0.1
        wheel_steering_arm_angle: -2.618
        steering_shaft_joint: steering_shaft_joint
      steering_motor:
        transport_name: front_transport
        controller_id: 1
        invert_direction: false
        position_offset: 0.0
      left_motor:
        transport_name: front_transport
        controller_id: 2
        motor_poles: 15
        invert_direction: false
        velocity_correction: 1.0
      right_motor:
        transport_name: front_transport
        controller_id: 3
        motor_poles: 15
        invert_direction: false
        velocity_correction: 1.0

    rear_axle:
      position_x: 0.0
      position_y: 0.0
      wheel_diameter: 0.3
      is_steered: false
      is_driven: true
      track: 0.7
      left_wheel_joint: rear_left_wheel_joint
      right_wheel_joint: rear_right_wheel_joint
      left_motor:
        transport_name: rear_transport
        controller_id: 2
        motor_poles: 15
        invert_direction: false
        velocity_correction: 1.0
      right_motor:
        transport_name: rear_transport
        controller_id: 3
        motor_poles: 15
        invert_direction: false
        velocity_correction: 1.0

transport_mapping:
  - transport_name: front_transport
    controller_id: 1
    port: '/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.2:1.0'
  - transport_name: rear_transport
    controller_id: 1
    port: '/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.3:1.0'

